version: '3.7'
services:
  ratatoskr:
    image: ghcr.io/divanvisagie/ratatoskr:latest
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_ADMIN=${TELEGRAM_ADMIN}
      - TELEGRAM_USERS=${TELEGRAM_USERS}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - REDIS_URL=${REDIS_URL}
      - ROOT_DIR=/app/data
    volumes:
      - ${DATA_ROOT_DIR}:/app/data
    restart: always

  watchtower:
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=3600
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
